version: '3'
services:
  backend:
    image: container
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
#    volumes:
#      - backend-data:/backend/
  frontend:
    image: frontend
    container_name: frontend
    ports:
    - 8080:80
  